name: Run-selfhosted

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: deploy on-prem
      #run: docker run -d ubuntu --name my-test
      run: echo "It works!"
